services:
  - type: web
    name: basketball-referee-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: MODEL_URL
        sync: false
    autoDeploy: false